package application;

import javafx.fxml.FXML;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;


public class AddEfficiencyController 
{
	@FXML
	private TextField target;
	@FXML
	private TextField present;
	@FXML
	private TextField rejection;
	@FXML
	private TextField bww;
	@FXML
	private TextField bwo;
	@FXML
	private TextField iiw;
	@FXML
	private TextField id;
	@FXML
	private TextField dd;
	@FXML
	private TextField nod;
	@FXML
	private TextField mm;
	@FXML
	private TextField yy;

	// Event Listener on Button.onAction
	@FXML
	public void addToDatabase(ActionEvent e) 
	{
		// TODO Autogenerated
		double fans1=Double.parseDouble(target.getText());
		double fans2=Double.parseDouble(present.getText());
		double fans3=Double.parseDouble(rejection.getText());
		double fans=(fans1/2+fans2/2+fans3/2)/3;
		double b1=Double.parseDouble(bww.getText());
		double b2=Double.parseDouble(bwo.getText());
		double b3=Double.parseDouble(iiw.getText());
		double b=b1+b2+b3;
		double fans4=fans+b;
		int id1=Integer.parseInt(id.getText());
		int dd1=Integer.parseInt(dd.getText());
		int mm1=Integer.parseInt(mm.getText());
		int yy1=Integer.parseInt(yy.getText());
		String date=dd1+"/"+mm1+"/"+yy1;
		int nod1=Integer.parseInt(nod.getText());
		
		try 
		{ 
			String url = "jdbc:mysql://localhost:3306/factory"; 
			Connection conn = (Connection) DriverManager.getConnection(url,"root","root"); 
			String query = "INSERT INTO displaymonthly ( id, nod, date, target, present, rejection, bww, bwo, iiw, overalleff, month)" + " values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
			PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
			ps.setInt (1, id1);
			ps.setInt (2, nod1);
			ps.setString (3, date);
			ps.setDouble (4, fans1 );
			ps.setDouble (5, fans2 );
			ps.setDouble (6, fans3 );
			ps.setDouble (7, b1 );
			ps.setDouble (8, b2);
			ps.setDouble (9, b3 );
			ps.setDouble (10, fans4 );
			ps.setInt(11, mm1);
			ps.execute();
			
			Stage dialogStage = new Stage();
		    dialogStage.initModality(Modality.WINDOW_MODAL);

		    VBox vbox = new VBox(new Text("Added Successfully!!!"));
		    vbox.setAlignment(Pos.CENTER);
		    vbox.setPadding(new Insets(15));
		    vbox.setPrefSize(400, 100);

		    dialogStage.setScene(new Scene(vbox));
		    dialogStage.show();
		    
			conn.close();
		} 
		catch (Exception e1) 
		{
			
			System.out.println(e);
    	
        } 
	}
	// Event Listener on Button.onAction
	@FXML
	public void getValues(ActionEvent event) 
	{
		
		int t1=Integer.parseInt(id.getText());
		int nodays=Integer.parseInt(nod.getText());
		int d=Integer.parseInt(dd.getText());
		int m=Integer.parseInt(mm.getText());
		int y=Integer.parseInt(yy.getText());
		
		int seop=0,saop=0,srej=0;
		int diff=0;
		double x=0,xy=0,xyz=0;
		
		try 
		{ 
			String url = "jdbc:mysql://localhost:3306/factory"; 
            Connection conn = (Connection) DriverManager.getConnection(url,"root","root"); 
            PreparedStatement ps = conn.prepareStatement("Select * from dailyinput where id="+t1);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next())
            {
            	//System.out.println(rs.getString(2));
            	
            	int d1=rs.getInt(3);
				int m1=rs.getInt(4);
				int y1=rs.getInt(5);
				
				if(d1==d &&m1==m &&y1==y)
				{
					//System.out.println("HI");
					
					do
					{
						int d2=rs.getInt(3);
						seop=seop+rs.getInt(13);
						saop=saop+rs.getInt(14);
						srej=srej+rs.getInt(16);
						//System.out.println(d2+" "+seop+" "+saop);
						if(d!=d2)
						{
							diff=diff+(d2-d);
							d=d2;
						}
						d++;
					}while(rs.next());
				}
				
				x=(seop-saop);
				xy=x/seop;
				xyz=100-(xy*100);
				
				//double d = 2.34568;
			    DecimalFormat f = new DecimalFormat("##.00");
			    //System.out.println(f.format(d));
				target.setText(""+f.format(xyz));
				x=(saop-srej);
				xy=x/saop;
				xyz=100-(100-(xy*100));
				rejection.setText(f.format(xyz)+"");
				check(diff,nodays,m);
            }
		}
		catch (SQLException e) 
		{
			e.printStackTrace();
		}
		
	}
	public void check(int down,int noofd,int m)
	{
		double x=0,y=0,z=0;
		if(m==2)
		{
			x=28-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");
		}
		if(m==1)
		{
			x=31-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");		}
		if(m==3)
		{
			x=31-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");		}
		if(m==4)
		{
			x=30-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");		}
		if(m==5)
		{
			x=31-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");}
		if(m==6)
		{
			x=30-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");}
		if(m==7)
		{
			x=31-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");}
		if(m==8)
		{
			x=31-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");}
		if(m==9)
		{
			x=30-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");}
		if(m==10)
		{
			x=31-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");}
		if(m==11)
		{
			x=30-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");}
		if(m==12)
		{
			x=31-noofd;
			down=(int) (down-x);
			y=(double)down/noofd;
			y=y*100;
			z=100-y;
		    DecimalFormat f = new DecimalFormat("##.00");

			present.setText(f.format(z)+"");}
	}
}
