package application;

import javafx.fxml.FXML;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import javafx.scene.text.Text;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.event.ActionEvent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class AddUserController 
{
	@FXML
	private TextField username;
	@FXML
	private TextField password;
	@FXML
	private Button AddUser;
	@FXML
	private Label status;
		

	// Event Listener on Button.onAction
	@FXML
	public void addUser(ActionEvent event) 
	{
		// TODO Autogenerated
		String username1="",password1="";
		Boolean flag=false,flag1=false;
	
		try
		{
			username1 = username.getText();
			password1 = password.getText();
			flag=check(username1,password1);
		}
		catch(Exception e)
		{
			//status.setText("Enter valid credentials");
			Stage dialogStage = new Stage();
		    dialogStage.initModality(Modality.WINDOW_MODAL);

		    VBox vbox = new VBox(new Text("Enter valid credentials"));
		    vbox.setAlignment(Pos.CENTER);
		    vbox.setPadding(new Insets(15));
		    vbox.setPrefSize(400, 100);

		    dialogStage.setScene(new Scene(vbox));
		    dialogStage.show();

		}
			
		if(flag==false)
		{
			//status.setText("Enter valid credentials");

			Stage dialogStage = new Stage();
		    dialogStage.initModality(Modality.WINDOW_MODAL);

		    VBox vbox = new VBox(new Text("Enter valid credentials"));
		    vbox.setAlignment(Pos.CENTER);
		    vbox.setPadding(new Insets(15));
		    vbox.setPrefSize(400, 100);

		    dialogStage.setScene(new Scene(vbox));
		    dialogStage.show();

		}
		else
		{
			
			try 
			{
				String url = "jdbc:mysql://localhost:3306/factory"; 
				Connection conn = (Connection) DriverManager.getConnection(url,"root","root"); 
				String query = "INSERT INTO user ( id, password)" + " values (?, ?)";
				PreparedStatement ps = (PreparedStatement) conn.prepareStatement(query);
				ps.setString (1, username1);
				ps.setString (2, password1);
				flag1=checkDatabase(username1,password1);
				if(flag1==true)
				{
					ps.executeUpdate();
					Stage dialogStage = new Stage();
					dialogStage.initModality(Modality.WINDOW_MODAL);

				    VBox vbox = new VBox(new Text("Added SuccessFully!!!"));
				    vbox.setAlignment(Pos.CENTER);
				    vbox.setPadding(new Insets(15));
				    vbox.setPrefSize(400, 100);
	
				    dialogStage.setScene(new Scene(vbox));
				    dialogStage.show();
				}
				else
				{
					Stage dialogStage = new Stage();
					dialogStage.initModality(Modality.WINDOW_MODAL);

				    VBox vbox = new VBox(new Text("User is already present!!!"));
				    vbox.setAlignment(Pos.CENTER);
				    vbox.setPadding(new Insets(15));
				    vbox.setPrefSize(400, 100);
	
				    dialogStage.setScene(new Scene(vbox));
				    dialogStage.show();
					
				}

			}
			catch(Exception e1)
			{
				//status.setText("Enter valid credentials");
				
				Stage dialogStage = new Stage();
			    dialogStage.initModality(Modality.WINDOW_MODAL);

			    VBox vbox = new VBox(new Text("Enter valid credentials"));
			    vbox.setAlignment(Pos.CENTER);
			    vbox.setPadding(new Insets(15));
			    vbox.setPrefSize(400, 100);

			    dialogStage.setScene(new Scene(vbox));
			    dialogStage.show();

			}
		}
	}
		
	private Boolean checkDatabase(String username1, String password1) throws SQLException 
	{
		// TODO Auto-generated method stub
		String url = "jdbc:mysql://localhost:3306/factory"; 
		Connection conn = (Connection) DriverManager.getConnection(url,"root","root"); 
		//String query = "INSERT INTO user ( id, password)" + " values (?, ?)";
		PreparedStatement ps = (PreparedStatement) conn.prepareStatement("Select * from employee");
		//ps=con.prepareStatement();
		ResultSet rs=ps.executeQuery();
		while(rs.next())
		{
			if(rs.getString(1)==username1)
			{
				return false;
			}
			
			
		}
		return true;
		
		
	}

	public boolean check(String ffname,String llname)
	{
		if(username.getText().trim().isEmpty()|| password.getText().trim().isEmpty())
		{
			return false;
		}
		else
		{
			return true;
		}
	}
}
