package application;

import javafx.fxml.FXML;

import javafx.scene.chart.LineChart;
import javafx.scene.chart.XYChart;
import javafx.scene.control.TextField;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.event.ActionEvent;

public class compareEmployeeController {
	@FXML
	private TextField id;
	@FXML
	private LineChart<String,Number> linechart;

	private Connection con = null;
	private PreparedStatement ps = null;
	private ResultSet rs = null;
	int d=0;
	double xyz=0,xy=0;

	// Event Listener on Button.onAction
	@FXML
	public void showGraph(ActionEvent event) 
	{
		// TODO Autogenerated
		XYChart.Series<String,Number> series=new XYChart.Series<String,Number>();
		 try 
		 {
			 con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/factory","root","root");
			int t=Integer.parseInt(id.getText()); 
			System.out.println("you"+t);
			ps=con.prepareStatement("Select * from displaymonthly where month="+t);
			rs=ps.executeQuery();
			while(rs.next())
			{
				
				
					d=rs.getInt(1);
					xyz=rs.getDouble(10);
					series.getData().add(new XYChart.Data<String,Number>(d+"",xyz));
				
			}
		 } 
		 catch (SQLException e) 
		 {
			// TODO Auto-generated catch block
			e.printStackTrace();
			
		}
		linechart.getData().add(series);
	}
}
