package application;

import javafx.fxml.FXML;

import javafx.scene.chart.LineChart;
import javafx.scene.chart.XYChart;
import javafx.scene.control.TextField;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.event.ActionEvent;

public class DisplayGraphController {
	@FXML
	private TextField id;
	@FXML
	private LineChart<String, Number> linechart;
	@FXML
	private TextField m;
	private Connection con = null;
	private PreparedStatement ps = null;
	private ResultSet rs = null;
	int d=0,x=0,y=0;
	double xyz=0,xy=0;

	// Event Listener on Button.onAction
	@FXML
	public void showGraph(ActionEvent event) {
		// TODO Autogenerated
		XYChart.Series<String,Number> series=new XYChart.Series<String,Number>();
		 try 
		 {
			 con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/factory","root","root");
			int t=Integer.parseInt(id.getText()); 
			ps=con.prepareStatement("Select * from dailyinput where id="+t);
			rs=ps.executeQuery();
			while(rs.next())
			{
				int m1=rs.getInt(4);
				int m2=Integer.parseInt(m.getText());		
				if(m1==m2)
				{
					d=rs.getInt(3);
					x=rs.getInt(13);
					y=rs.getInt(14);
					xy=x-y;
					xyz=(double)xy/x;
					xyz=100-xyz*100;
					System.out.println("EFF"+xyz);
					series.getData().add(new XYChart.Data<String,Number>(d+"",xyz));
				}
			}
		 } 
		 catch (SQLException e) 
		 {
			// TODO Auto-generated catch block
			e.printStackTrace();
			
		}
		linechart.getData().add(series);
	}
}
