package application;

import javafx.fxml.FXML;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.XYChart;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


public class MonthlyGraphController 
{
	@FXML
	private TextField id;
	@FXML
	private LineChart<String,Number> linechart;
	@FXML
	private TextField m;
	private Connection con = null;
	private PreparedStatement ps = null;
	private ResultSet rs = null;

	double d=0.0;

	// Event Listener on Button.onAction
	@FXML
	public void showGraph(ActionEvent event) 
	{
		// TODO Autogenerated
		XYChart.Series<String,Number> series=new XYChart.Series<String,Number>();
		 try 
		 {
			 con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/factory","root","root");
			int t=Integer.parseInt(id.getText()); 
			ps=con.prepareStatement("Select * from displaymonthly where id="+t);
			rs=ps.executeQuery();
			while(rs.next())
			{
					int  s=rs.getInt(11);
					if(s==1)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("January",d));
					}
					if(s==2)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("Febuary",d));
					}
					if(s==3)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("March",d));
					}
					if(s==4)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("April",d));
					}
					if(s==5)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("May",d));
					}
					if(s==6)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("June",d));
					}
					if(s==7)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("July",d));
					}if(s==8)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("August",d));
					}if(s==9)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("September",d));
					}if(s==10)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("October",d));
					}if(s==11)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("November",d));
					}if(s==12)
					{
						d=rs.getDouble(10);
						series.getData().add(new XYChart.Data<String,Number>("December",d));
					}
				
			}
			
		 } 
		 catch (SQLException e) 
		 {
			// TODO Auto-generated catch block
			e.printStackTrace();
			
		}
		linechart.getData().add(series);
	}
}

