package application;

import javafx.fxml.FXML;

import javafx.scene.chart.LineChart;
import javafx.scene.chart.XYChart;
import javafx.scene.control.TextField;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.event.ActionEvent;

public class YearlyGraphController {
	@FXML
	private TextField id;
	@FXML
	private LineChart<String,Number> linechart;
	@FXML
	private TextField m;
	private Connection con = null;
	private PreparedStatement ps = null;
	private ResultSet rs = null;

	double d=0.0;

	// Event Listener on Button.onAction
	@FXML
	public void showGraph(ActionEvent event) {
		// TODO Autogenerated
		System.out.println("afhhhhh");
		XYChart.Series<String,Number> series=new XYChart.Series<String,Number>();
		 try 
		 {
			 con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/factory","root","root");
			int t=Integer.parseInt(id.getText()); 
			ps=con.prepareStatement("Select * from displaymonthly where id="+t);
			rs=ps.executeQuery();
			while(rs.next())
			{
				
					d=rs.getDouble(10);
					series.getData().add(new XYChart.Data<String,Number>(d+"",d));
				
			}
		 } 
		 catch (SQLException e) 
		 {
			// TODO Auto-generated catch block
			e.printStackTrace();
			
		}
		linechart.getData().add(series);
	}
	}

